apiVersion: v1
kind: Secret
metadata:
  name: timeshaasan-secrets
  namespace: default
type: Opaque
data:
  client-secret: cVBVTHBValplOGVFdnFqUXlXVnRMZEY1U0RBQnQzcjJ1MHg4cGRUY3VhSQ==
  smtp_hostname: c210cC5tYWlsZ3VuLm9yZw==
  smtp_username: VGltZVNoYWFzYW4=
  smtp_email: dGltZXNoYWFzYW4tbm9yZXBseUBxdWFudGdhbS5jb20K
  smtp_password: OGZiYjBlOTYxOGIyOWI3NmViNDJiZWEwOTQxYTVlNjktN2EzYWY0NDItMDlhYWY3NDk=
